### ISSUE TITLE
[Errno 2] No such file or directory: 'weights\\realesr-general-x4v3-cat.pth'

### ISSUE THREAD

**Issue by xushuanglong** [Lemonononon/Real-ESRGAN-TRT#1]
Hello boss, may I ask where to download realesr-universal-x4v3-cat.pth? Or should the code be: Model Path=Model Path. replace ('realesr-General-x4v3 ','realesr-General-x4v3 cat') model_path = model_path = model_path.replace('realesr-general-x4v3', 'realesr-general-wdn-x4v3')？

**Comment by Lemonononon** [comment]
Please check the bolded sections in the README.
Confirm the model you need by referring to this repository [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN) first. If you need both realesr-general-x4v3 and realesr-general-wdn-x4v3, you have to average the weights according to the [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN/blob/master/inference_realesrgan.py) when loading realesr-general-x4v3 model.

**Comment by xushuanglong** [comment]
Okay, actually I have downloaded both of the models you mentioned and modified the code to generate WTS files. However, when I inferred the 400X400 size image on Orin, the accuracy of FP16 could only reach 90ms, which is not real-time. May I ask how much time it took for you to test it yourself?

**Comment by Lemonononon** [comment]
我没有Jetson设备来测试，只用过3080和3090做测试；你可以详细测试一下是哪部分耗时比较多，前后处理用CUDA重写应该会快一些

**Comment by xushuanglong** [comment]
请问您在3080和3090上的表现如何呢，可以达到实时哈

**Comment by Lemonononon** [comment]
3080 300*450的图像，前处理加上推理是25ms左右，batchsize为1

**Comment by xushuanglong** [comment]
好的，我在orin上400X400,前处理加推理是90ms,batchsize为1，谢谢您！
